### PR TITLE
INS-21791 OpenSearch Alerting & Notifications Egress Rules Endpoints

### PR DESCRIPTION
**Pull request by Jack-Kilrain**

### CODE REVIEW

**Comment by niluka-insta** [comment]
Like V1, we need to do a version bump for V2 as well.

**Comment by Jack-Kilrain** [comment]
@niluka-insta I presume that it's just bumping the version in the `Makefile`? I can't seem to find any mention of how we do version bumps in the docs, but I could be missing something.

**Comment by niluka-insta** [comment]
@Jack-Kilrain yes that is correct. 
It looks like it is currently only covered in the Deployment procedure doco in https://instaclustr.atlassian.net/wiki/spaces/IDS/pages/2408939533/Terraform+Provider+v2+deployment+procedure

**Review by niluka-insta — APPROVED** [review]
LGTM

**Review by iclonghoang — APPROVED** [review]

**Pull request merged**
